# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aafac2e1b690e81f3797465efaad7ae5a3c494e1ebbbae7b9ad315728f281ed87f40d8f11584bc4367d530aed2e369e7aa91763968bf10055f9ea1258dec886a

test:
  secret_key_base: e8bf70b0e518cb0547ed0e080daa865523b09f4b40c98d6e2e5b053e455624b225a03a2368d9efc7b93487d90be610284fb72eec6b7a9f594577918a8a0855ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
